### ISSUE TITLE
Adicionar licença 

### ISSUE THREAD

**Issue by thiago-scherrer** [jonascavalcantineto/tshootsys#1]
Pra iniciar o projeto, acho que podemos começar adicionando a licença. Oq acha de GNU GPLv3?

**Comment by jonascavalcantineto** [comment]
@thiago-scherrer ja  com a licença GPL

**Comment by thiago-scherrer** [comment]
Vdd => https://github.com/jonascavalcantineto/tshootsys/blob/main/LICENSE
